credentials:
  usernames:
    uzoma:
      email: uzyivy@gmail.com
      logged_in: False # Will be managed automatically
      name: Obi Uzoma
      password: abc # Will be hashed automatically
    uzy:
      email: efuna@gmail.com
      logged_in: False # Will be managed automatically
      name: Ezife Uzoma
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com